const items = [
    {
        id: 11,
        imageSrc: '/images/gallery/logo_design/logo1.webp',
        title: 'Item 10',
        type : 2,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 12,
        imageSrc: '/images/gallery/logo_design/logo2.png',
        title: 'Item 10',
        type : 2,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 13,
        imageSrc: '/images/gallery/logo_design/logo3.jpg',
        title: 'Item 10',
        type : 2,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 14,
        imageSrc: '/images/gallery/logo_design/logo4.jpg',
        title: 'Item 10',
        type : 2,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 15,
        imageSrc: '/images/gallery/logo_design/logo5.png',
        title: 'Item 10',
        type : 2,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 16,
        imageSrc: '/images/gallery/mascot_design/mascot1.jpg',
        title: 'Item 10',
        type : 3,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 17,
        imageSrc: '/images/gallery/mascot_design/mascot2.jpg',
        title: 'Item 10',
        type : 3,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 18,
        imageSrc: '/images/gallery/mascot_design/mascot3.jpg',
        title: 'Item 10',
        type : 3,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 19,
        imageSrc: '/images/gallery/mascot_design/mascot4.jpg',
        title: 'Item 10',
        type : 3,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 20,
        imageSrc: '/images/gallery/mascot_design/mascot4.png',
        title: 'Item 10',
        type : 3,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 1,
        imageSrc: '/images/gallery/other/gallery1.png',
        title: 'Item 1',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id:2,
        imageSrc: '/images/gallery/other/ourdesign.svg',
        title: 'Item 2',
        type : 6,
    },
    {
        id: 3,
        imageSrc: '/images/gallery/other/gallery3.png',
        title: 'Item 3',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 4,
        imageSrc: '/images/gallery/other/gallery4.png',
        title: 'Item 1',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 5,
        imageSrc: '/images/gallery/other/gallery5.png',
        title: 'Item 5',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 6,
        imageSrc: '/images/gallery/other/gallery6.png',
        title: 'Item 6',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 7,
        imageSrc: '/images/gallery/other/gallery7.png',
        title: 'Item 7',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 8,
        imageSrc: '/images/gallery/other/gallery8.png',
        title: 'Item 8',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 9,
        imageSrc: '/images/gallery/other/gallery9.png',
        title: 'Item 3',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 10,
        imageSrc: '/images/gallery/other/gallery10.png',
        title: 'Item 10',
        type : 6,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 21,
        imageSrc: '/images/gallery/packaging_design/packaging1.jpg',
        title: 'Item 10',
        type : 4,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 22,
        imageSrc: '/images/gallery/packaging_design/packaging2.png',
        title: 'Item 10',
        type : 4,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 23,
        imageSrc: '/images/gallery/packaging_design/packaging3.jpg',
        title: 'Item 10',
        type : 4,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 24,
        imageSrc: '/images/gallery/packaging_design/packaging4.png',
        title: 'Item 10',
        type : 4,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 25,
        imageSrc: '/images/gallery/packaging_design/packaging5.jpg',
        title: 'Item 10',
        type : 4,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 26,
        imageSrc: '/images/gallery/photography/photography1.jpg',
        title: 'Item 10',
        type : 5,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 27,
        imageSrc: '/images/gallery/photography/photography2.jpg',
        title: 'Item 10',
        type : 5,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 28,
        imageSrc: '/images/gallery/photography/photography3.jpg',
        title: 'Item 10',
        type : 5,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 29,
        imageSrc: '/images/gallery/photography/photography4.jpg',
        title: 'Item 10',
        type : 5,
        desc : 'Lorem ipsum dolor sit amet.',
    },
    {
        id: 30,
        imageSrc: '/images/gallery/photography/photography5.jpg',
        title: 'Item 10',
        type : 5,
        desc : 'Lorem ipsum dolor sit amet.',
    },

];

export default items;